INSERT INTO #temp_table SELECT ID_NUMBER, CIF_KEY, CUSTOMER_NAME, CIF_OPEN_BRANCH_CODE, CIF_OPEN_BRANCH, CUST_TYPE_CODE, CIF_OPEN_REGION_CODE, CIF_OPEN_REGION, SEGMENT_DIV_OWNER, SUB_SEGMENT, DIR_OWNER, ACCOUNT_TYPE, SUB_CATEGORY, PRODUCT_NAME, CURRENCY, BRANCH_CODE, SUBBRANCH_CODE, ACCT_APPROVAL_DATE, ACCT_OPEN_DATE, ACCT_EXPIRY_DATE, GL_CLASS_CODE, GL_ACCOUNT_ID, MARKET_SEGMENT_CD, ACCOUNT_STATUS, RATE, APPROVAL_AMT, APPROVAL_AMT_IDR, CUR_BOOK_BAL, CUR_BOOK_BAL_IDR, NO_PK, ADM_FEE, ID_BANK_GARANSI, JAMINAN, CHANNEL_OWNER_L1, CHANNEL_TYPE_L1, CHANNEL_OWNER_L2, CHANNEL_TYPE_L2, CHANNEL_OWNER_L3, CHANNEL_TYPE_L3, CHANNEL_OWNER_MIRROR, AS_OF_DATE FROM ACL_DATALAKE.MART_CTA CTA
LEFT JOIN DM_CUSTOMER.CUSTOMER_ICONS CUST
ON CTA.CIF_KEY = CUST.CIF_KEY
AND CUST.AS_OF_DATE = @TANGGAL_POSISI
LEFT JOIN (
    SELECT
        *
    FROM 
    (
        SELECT 
            CHANNEL.*
            , ROW_NUMBER() OVER(PARTITION BY ID_NUMBER ORDER BY AS_OF_DATE DESC) RN
        FROM 
        (
            SELECT DISTINCT
                CIF_KEY
                , ID_NUMBER
                , SEGMENT_DIV_OWNER
                , CHANNEL_OWNER_L1
                , CHANNEL_TYPE_L1
                , CHANNEL_OWNER_L2
                , CHANNEL_TYPE_L2
                , CHANNEL_OWNER_L3
                , CHANNEL_TYPE_L3
                , CHANNEL_OWNER_MIRROR
                , AS_OF_DATE
            FROM acl_datalake.mart_master_channel_baseline 
            UNION ALL
            SELECT 
                CIF_KEY
                , ID_NUMBER
                , SEGMENT_DIV_OWNER
                , CHANNEL_OWNER_L1
                , CHANNEL_TYPE_L1
                , CHANNEL_OWNER_L2
                , CHANNEL_TYPE_L2
                , CHANNEL_OWNER_L3
                , CHANNEL_TYPE_L3
                , CHANNEL_OWNER_MIRROR
                , AS_OF_DATE
            FROM acl_datalake.mart_master_channel_nwow_daily
        ) AS CHANNEL
    ) AS CHANNEL ) AS CHANNEL ON CTA.ID_NUMBER = CHANNEL.ID_NUMBER
AND CTA.AS_OF_DATE = CHANNEL.AS_OF_DATE;
INSERT INTO PRD_ACL_DATALAKE.MASTER_CTA PARTITION(as_of_date) SELECT ID_NUMBER, CIF_KEY, CUSTOMER_NAME, CIF_OPEN_BRANCH_CODE, CIF_OPEN_BRANCH, CUST_TYPE_CODE, CIF_OPEN_REGION_CODE, CIF_OPEN_REGION, SEGMENT_DIV_OWNER, SUB_SEGMENT, DIR_OWNER, ACCOUNT_TYPE, SUB_CATEGORY, PRODUCT_NAME, CURRENCY, BRANCH_CODE, SUBBRANCH_CODE, ACCT_APPROVAL_DATE, ACCT_OPEN_DATE, ACCT_EXPIRY_DATE, GL_CLASS_CODE, GL_ACCOUNT_ID, MARKET_SEGMENT_CD, ACCOUNT_STATUS, RATE, APPROVAL_AMT, APPROVAL_AMT_IDR, CUR_BOOK_BAL, CUR_BOOK_BAL_IDR, NO_PK, ADM_FEE, ID_BANK_GARANSI, JAMINAN, CHANNEL_OWNER_L1, CHANNEL_TYPE_L1, CHANNEL_OWNER_L2, CHANNEL_TYPE_L2, CHANNEL_OWNER_L3, CHANNEL_TYPE_L3, CHANNEL_OWNER_MIRROR, AS_OF_DATE FROM #temp_table;
