INSERT INTO #temp_table SELECT 
  JT.ID_NUMBER AS ID_NUMBER
, JT.BNI_TELLER_ID AS TELLER_ID
, JT.CUR_GROSS_RATE AS CUR_GROSS_RATE
, JT.BNI_BAL_BLOCK_DATE AS BLOCKED_DATE
, JT.ORG_BOOK_BAL AS ORG_BOOK_BAL
, JT.AVG_BOOK_BAL AS AVG_BOOK_BAL
, JT.BNI_DEBIT_TRX_TODAY AS DEBIT_TRX_TODAY
, JT.BNI_CREDIT_TRX_TODAY AS CREDIT_TRX_TODAY
, JT.BNI_INTEREST_AMOUNT AS INTEREST_AMOUNT
, JT.BNI_DAILY_INTEREST_AMOUNT AS DAILY_INTEREST_AMT
, JT.BNI_CASH_INT_PAYABLE AS CASH_INT_PAYABLE
, JT.BNI_CERTIFICATE_NO AS CERTIFICATE_NO
, JT.BNI_INT_TAX_AMT AS INT_TAX_AMT
, JT.BNI_BLOCK_REASON AS BLOCK_REASON 
, JT.BNI_YESTERDAY_END_BAL AS YESTERDAY_END_BAL
, JT.BNI_LOWEST_BAL AS LOWEST_BAL
, JT.BNI_HIGHEST_BAL AS HIGHEST_BAL
, JT.BNI_ACC_BLOCK_DATE AS ACC_BLOCK_DATE
, JT.BNI_LAST_TRX_DATE AS LAST_TRX_DATE
, JT.BNI_LAST_EOY_BAL AS LAST_EOY_BAL
, JT.TAPENAS_ARO_FLAG AS TAPENAS_ARO_FLAG
, JT.BNI_BLOCK_USER_ID AS BLOCK_USER_ID
, JT.BNI_LAST_MASTER_UPDATE_USER_ID AS LAST_MASTER_UPDATE_USER_ID
, JT.BNI_INT_RATE_UPDATE_USER_ID AS INT_RATE_UPDATE_USER_ID 
, JT.BNI_ROLLOVER_STATUS AS ROLLOVER_STATUS
, JT.BNI_ACC_CLOSE_USER_ID AS ACC_CLOSE_USER_ID
, JT.AS_OF_DATE AS AS_OF_DATE

FROM 
(
			 SELECT
			   SRI_155_101_JT0001DEPX.ID_NUMBER AS ID_NUMBER
			 , SRI_155_101_JT0001DEPX.CUR_GROSS_RATE AS CUR_GROSS_RATE
			 , SRI_155_101_JT0001DEPX.BNI_BAL_BLOCK_DATE AS BNI_BAL_BLOCK_DATE
			 , SRI_155_101_JT0001DEPX.BNI_INTEREST_AMOUNT AS BNI_INTEREST_AMOUNT
			 , SRI_155_101_JT0001DEPX.BNI_DAILY_INTEREST_AMOUNT AS BNI_DAILY_INTEREST_AMOUNT
			 , SRI_155_101_JT0001DEPX.BNI_DEBIT_TRX_TODAY AS BNI_DEBIT_TRX_TODAY
			 , SRI_155_101_JT0001DEPX.BNI_CREDIT_TRX_TODAY AS BNI_CREDIT_TRX_TODAY
			 , Cast(NULL AS DECIMAL(17,2)) AS BNI_CASH_INT_PAYABLE
			 , Cast(NULL AS VARCHAR(20)) AS BNI_CERTIFICATE_NO
			 , Cast(NULL AS DECIMAL(17,2)) AS ORG_BOOK_BAL
			 , SRI_155_101_JT0001DEPX.BNI_INT_TAX_AMOUNT AS BNI_INT_TAX_AMT
			 , Cast(SRI_155_101_JT0001DEPX.AVG_BOOK_BAL AS DECIMAL (17,2)) AS  AVG_BOOK_BAL
			 , Cast(SRI_155_101_JT0001DEPX.BNI_BLOCK_REASON AS VARCHAR(50)) AS BNI_BLOCK_REASON
			 
			 , Cast(SRI_155_101_JT0001DEPX.BNI_YESTERDAY_END_BAL AS DECIMAL(17,2)) AS BNI_YESTERDAY_END_BAL
			 , Cast(SRI_155_101_JT0001DEPX.BNI_LOWEST_BAL AS DECIMAL(17,2)) AS BNI_LOWEST_BAL
			 , Cast(SRI_155_101_JT0001DEPX.BNI_HIGHEST_BAL AS DECIMAL(17,2)) AS BNI_HIGHEST_BAL
			 , SRI_155_101_JT0001DEPX.BNI_ACC_BLOCK_DATE
			 
			, Cast(SRI_155_101_JT0001DEPX.BNI_LAST_TRX_DATE AS DATE ) AS BNI_LAST_TRX_DATE
			, Cast(SRI_155_101_JT0001DEPX.BNI_LAST_EOY_BAL AS DECIMAL (17,2)) AS BNI_LAST_EOY_BAL 
			, Cast(SRI_155_101_JT0001DEPX.TAPENAS_ARO_FLAG AS VARCHAR(1)) AS TAPENAS_ARO_FLAG
			, Cast(SRI_155_101_JT0001DEPX.BNI_TELLER_ID AS VARCHAR(10)) AS BNI_TELLER_ID
			, Cast(SRI_155_101_JT0001DEPX.BNI_BLOCK_USER_ID AS DECIMAL(5,0)) AS BNI_BLOCK_USER_ID
			, Cast(SRI_155_101_JT0001DEPX.BNI_LAST_MASTER_UPDATE_USER_ID AS DECIMAL(5,0)) AS BNI_LAST_MASTER_UPDATE_USER_ID
			,Cast(NULL AS DECIMAL(5,0)) AS BNI_INT_RATE_UPDATE_USER_ID
			,Cast(NULL AS VARCHAR(4)) AS BNI_ROLLOVER_STATUS
			, SRI_155_101_JT0001DEPX.BNI_ACC_CLOSE_USER_ID AS BNI_ACC_CLOSE_USER_ID
			, SRI_155_101_JT0001DEPX.DATE_PROCESS AS AS_OF_DATE

			 FROM prd_sri_datalake.sri_155_103_jt0001depx AS SRI_155_101_JT0001DEPX
			  UNION ALL
			  
			 SELECT
			   SRI_155_102_JT0001FIXD.ID_NUMBER AS ID_NUMBER
			 , SRI_155_102_JT0001FIXD.CUR_GROSS_RATE AS CUR_GROSS_RATE
			 , SRI_155_102_JT0001FIXD.BNI_BAL_BLOCK_DATE AS BNI_BAL_BLOCK_DATE
			 , SRI_155_102_JT0001FIXD.BNI_INT_AMT_GROSS AS BNI_INTEREST_AMOUNT
			 , SRI_155_102_JT0001FIXD.BNI_DAILY_INTEREST_AMOUNT AS BNI_DAILY_INTEREST_AMOUNT
			 , Cast(NULL AS DECIMAL(17,2)) AS BNI_DEBIT_TRX_TODAY
			 , Cast(NULL AS DECIMAL(17,2)) AS BNI_CREDIT_TRX_TODAY
			 , SRI_155_102_JT0001FIXD.BNI_CASH_INT_PAYABLE AS BNI_CASH_INT_PAYABLE
			 , SRI_155_102_JT0001FIXD.BNI_CERTIFICATE_NO AS BNI_CERTIFICATE_NO
			 , SRI_155_102_JT0001FIXD.ORG_BOOK_BAL AS ORG_BOOK_BAL
			 , SRI_155_102_JT0001FIXD.BNI_INT_TAX_AMT AS BNI_INT_TAX_AMT
			 , Cast(NULL AS DECIMAL (17,2)) AS  AVG_BOOK_BAL
			 , Cast(NULL AS VARCHAR(50)) AS BNI_BLOCK_REASON

			 , Cast(NULL AS DECIMAL(17,2)) AS BNI_YESTERDAY_END_BAL
			 , Cast(NULL AS DECIMAL(17,2)) AS BNI_LOWEST_BAL
			 , Cast(NULL AS DECIMAL(17,2)) AS BNI_HIGHEST_BAL
			 , SRI_155_102_JT0001FIXD.BNI_ACC_BLOCK_DATE
			 
			, Cast(NULL AS DATE ) AS BNI_LAST_TRX_DATE
			, Cast(NULL AS DECIMAL (17,2)) AS BNI_LAST_EOY_BAL 
			, Cast(NULL AS VARCHAR(1)) AS TAPENAS_ARO_FLAG
			, Cast(SRI_155_102_JT0001FIXD.BNI_TELLER_ID AS VARCHAR(10)) AS BNI_TELLER_ID
			, Cast(NULL AS DECIMAL(5,0)) AS BNI_BLOCK_USER_ID
			, case when SRI_155_102_JT0001FIXD.bni_account_status = 7 then cast(SRI_155_102_JT0001FIXD.bni_acc_close_user_id as decimal(5,0)) else null end as BNI_LAST_MASTER_UPDATE_USER_ID 
			
			, SRI_155_102_JT0001FIXD.BNI_INT_RATE_UPDATE_USER_ID AS BNI_INT_RATE_UPDATE_USER_ID 
			, SRI_155_102_JT0001FIXD.BNI_ROLLOVER_STATUS AS BNI_ROLLOVER_STATUS
			, SRI_155_102_JT0001FIXD.BNI_ACC_CLOSE_USER_ID AS BNI_ACC_CLOSE_USER_ID
            		, SRI_155_102_JT0001FIXD.DATE_PROCESS AS AS_OF_DATE
            
			 FROM  prd_sri_datalake.sri_155_105_jt0001fixd AS SRI_155_102_JT0001FIXD) JT;
INSERT INTO prd_acl_datalake.MART_DPK_JT SELECT ID_NUMBER, TELLER_ID, CUR_GROSS_RATE, BLOCKED_DATE, ORG_BOOK_BAL, AVG_BOOK_BAL, DEBIT_TRX_TODAY, CREDIT_TRX_TODAY, INTEREST_AMOUNT, DAILY_INTEREST_AMT, CASH_INT_PAYABLE, CERTIFICATE_NO, INT_TAX_AMT, BLOCK_REASON, YESTERDAY_END_BAL, LOWEST_BAL, HIGHEST_BAL, ACC_BLOCK_DATE, LAST_TRX_DATE, LAST_EOY_BAL, TAPENAS_ARO_FLAG, BLOCK_USER_ID, LAST_MASTER_UPDATE_USER_ID, INT_RATE_UPDATE_USER_ID, ROLLOVER_STATUS, ACC_CLOSE_USER_ID, AS_OF_DATE FROM #temp_table;
