INSERT INTO #temp_table SELECT 
  SRI_101_118_INVM.ID_NUMBER
, SRI_101_118_INVM.CIF_KEY 
, SRI_101_118_INVM.ACCT_TYPE AS ACCOUNT_TYPE
, SRI_101_118_INVM.INT_CAT AS SUB_CATEGORY
, SRI_101_115_DEPP.DESCRIPT AS PRODUCT_NAME
, SRI_101_118_INVM.CURRENCY AS CURRENCY
, CAST(SRI_101_118_INVM.BRANCH_NO AS INTEGER) AS BRANCH_CODE
, CAST(COALESCE(SUBSTR(TRIM(SRI_101_118_INVM.GL_CLASS_CODE),20,2),'00') AS INTEGER_1) AS SUBBRANCH_CODE
, SRI_101_118_INVM.ACCT_OPEN_DT AS ACCT_OPEN_DATE
, SRI_101_118_INVM.ACCT_RENEWAL_DT AS ACCT_RENEWAL_DT
, CASE WHEN SRI_101_118_INVM.CURR_STATUS = '07' THEN SRI_101_118_INVM.LST_FIN_DT ELSE NULL END AS ACCT_CLOSE_DATE
, SRI_101_118_INVM.GL_CLASS_CODE AS GL_CLASS_CODE
, CAST(SUBSTR(SRI_101_118_INVM.GL_CLASS_CODE,8, 10) AS INTEGER) AS GL_ACCOUNT_ID
, SUBSTR(SRI_101_118_INVM.GL_CLASS_CODE,18, 4) AS MARKET_SEGMENT_CD
,CASE 
WHEN SRI_101_118_INVM.CURR_STATUS <> '07' AND SRI_101_115_DEPP.ACCT_DESC = 'T' AND CAST(SRI_101_118_INVM.NO_OF_STOPS AS INTEGER)>0 THEN '50'  
WHEN SRI_101_118_INVM.CURR_STATUS <> '07' AND SRI_101_115_DEPP.ACCT_DESC <> 'T' AND CAST(SRI_101_118_INVM.NO_OF_STOPS AS INTEGER)>0 THEN '08'  
ELSE SRI_101_118_INVM.CURR_STATUS 
END AS ACCOUNT_STATUS
, SRI_101_118_INVM.NO_OF_STOPS AS NO_OF_STOPS_STATUS
 
, CASE WHEN SRI_101_118_INVM.INT_FRM_DT > 2956565 THEN CAST('2999-12-31'AS DATE) 
    WHEN SRI_101_118_INVM.INT_FRM_DT  = 0 THEN CAST('1900-01-01' AS DATE) 
    ELSE date_add(CAST('1900-01-01' AS DATE), (SRI_101_118_INVM.INT_FRM_DT - 1)) END AS INT_FROM_DATE
 
, CASE WHEN SRI_101_118_INVM.INT_TO_DT > 2956565 THEN CAST('2999-12-31'AS DATE) 
    WHEN SRI_101_118_INVM.INT_TO_DT  = 0 THEN CAST('1900-01-01' AS DATE) 
    ELSE date_add(CAST('1900-01-01' AS DATE), (SRI_101_118_INVM.INT_TO_DT - 1)) END AS INT_TO_DATE

,CASE WHEN CAST(SRI_101_118_INVM.ACCT_TYPE AS INT) <> 2800 THEN SRI_101_118_INVM.MATURITY_DATE
       ELSE CASE WHEN day(SRI_101_118_INVM.acct_open_dt) > SRI_101_117_IADVYY.CAS_PAGE_NO THEN add_months(cast(concat(cast(year(add_months(SRI_101_118_INVM.acct_open_dt, 1)) AS string_1), '-', lpad(cast(month(add_months(SRI_101_118_INVM.acct_open_dt, 1)) AS string_2), 2, '0'), '-', lpad(cast(LEAST(CASE WHEN SRI_101_117_IADVYY.CAS_PAGE_NO = 0 THEN 1 ELSE SRI_101_117_IADVYY.CAS_PAGE_NO END, day(last_day(add_months(SRI_101_118_INVM.acct_open_dt, 1)))) AS string_3), 2, '0')) AS date_1),CASE WHEN SRI_101_115_DEPP.INSURANCE_FLG = 'I' THEN SRI_101_117_IADVYY.INSU_TERM ELSE 0 END)
	         ELSE add_months(cast(concat(cast(year(SRI_101_118_INVM.acct_open_dt) AS string_4), '-',lpad(cast(month(SRI_101_118_INVM.acct_open_dt) AS string), 2, '0'), '-',lpad(cast(LEAST(CASE WHEN SRI_101_117_IADVYY.CAS_PAGE_NO = 0 THEN 1 ELSE SRI_101_117_IADVYY.CAS_PAGE_NO END, day(last_day(SRI_101_118_INVM.acct_open_dt)))AS string), 2, '0')) AS date),CASE WHEN SRI_101_115_DEPP.INSURANCE_FLG = 'I' THEN SRI_101_117_IADVYY.INSU_TERM ELSE 0 END)
	         END 
       END AS MATURITY_DATE
, CASE WHEN TRIM(SRI_101_115_DEPP.ACCT_DESC) = 'T' THEN SRI_101_118_INVM.ORIGINAL_TERM ELSE NULL END AS ORG_TERM
, CASE WHEN TRIM(SRI_101_115_DEPP.ACCT_DESC) = 'T' THEN SRI_101_118_INVM.ORIGINAL_TERM_BASE ELSE NULL END AS ORG_TERM_MULT
, NULL AS TELLER_ID 
, SRI_101_118_INVM.VAR_INT_RATE AS SPECIAL_INT_RATE
, NULL AS CUR_GROSS_RATE 
, CURRENCY_RATE.RATE AS RATE
, NULL AS BLOCKED_DATE 
, SRI_101_118_INVM.HOLD_VAL AS BLOCKED_BALANCE
, SRI_101_118_INVM.DIV5 AS YTD_INTEREST
, SRI_101_118_INVM.INT_AVAILABLE AS INTEREST_ACCRUED
, NULL AS ORG_BOOK_BAL 
, SRI_101_118_INVM.CURR_BAL AS CUR_BOOK_BAL
, CAST(SRI_101_118_INVM.CURR_BAL AS DECIMAL(22,3)) * CAST(CURRENCY_RATE.RATE AS DECIMAL(22,3)) AS CUR_BOOK_BAL_IDR
, SRI_101_118_INVM.NET_AV_BAL_YTD AS NET_AV_BAL_YTD
, SRI_101_118_INVM.NET_AV_NO_YTD AS NET_AV_NO_YTD
, SRI_101_118_INVM.UNCL_CHQ_VAL AS CLR_TRX_TODAY
, NULL AS DEBIT_TRX_TODAY 
, NULL AS CREDIT_TRX_TODAY 
, NULL AS INTEREST_AMOUNT 
, NULL AS DAILY_INTEREST_AMT 
, SRI_101_118_INVM.CURR_BAL - SRI_101_118_INVM.NPB_VAL AS LAST_PRINT_BAL
, SRI_101_118_INVM.EOM_BAL AS LAST_EOM_BAL
, SRI_101_118_INVM.INT_INCR AS DAILY_INT_INCREMENT
 
, CASE WHEN to_date(date_sub(add_months(concat(from_unixtime(unix_timestamp(@tanggal_posisi,'yyyy-MM-dd'), 'yyyy-MM'),'-01'),1),1))= @tanggal_posisi 
    THEN SRI_101_118_INVM.DIV1 ELSE 0 
  END AS INTEREST_MTD
, SRI_101_118_INVM.INT_PROJ AS PROJECTED_INTEREST
, SRI_101_118_INVM.TRAP AS INT_PAY_METHOD

, NULL AS CASH_INT_PAYABLE 
, NULL AS CERTIFICATE_NO 

, CASE WHEN SRI_101_118_INVM.TRAP='T' THEN (CASE WHEN CAST(SRI_101_118_INVM.affiliated_acct_no AS BIGINT)=33 THEN 0 
												ELSE CAST(SRI_101_118_INVM.affiliated_acct_no AS BIGINT) END) 
	   ELSE (CASE WHEN LENGTH(CAST(CAST(SRI_101_117_IADVYY.AFFI_INSTL_AC AS BIGINT) AS VARCHAR(100))) >= 10 THEN CAST(SRI_101_117_IADVYY.AFFI_INSTL_AC AS BIGINT) 
	   			 WHEN CAST(SRI_101_117_IADVYY.tapenas_acct AS BIGINT)=33 THEN 0
	   			 ELSE CAST(SRI_101_117_IADVYY.tapenas_acct AS BIGINT) 
				 END) 
	   END AS AFFILIATED_ACCT_NO
, CASE WHEN SRI_101_115_DEPP.INSURANCE_FLG = 'I' THEN SRI_101_117_IADVYY.PRINCIPAL_ARREARS ELSE 0 END AS TAP_MONTHLY_ARREAR
, CASE WHEN SRI_101_115_DEPP.INSURANCE_FLG = 'I' THEN SRI_101_117_IADVYY.MTH_INSTAL_AMT ELSE 0 END AS TAPENAS_MTH_PAY
, SRI_101_117_IADVYY.PROJ_MTH_ACTY_DEP AS PROJ_MTH_ACTY_DEP
, SRI_101_117_IADVYY.PROJ_MTH_ACTY_WDL AS PROJ_MTH_ACTY_WDL  
, CASE WHEN CAST(SRI_101_117_IADVYY.OPEN_ACCT_RESN AS INTEGER) = 1 THEN 'Personal'
    WHEN CAST(SRI_101_117_IADVYY.OPEN_ACCT_RESN AS INTEGER) = 2 THEN 'Investasi' 
    WHEN CAST(SRI_101_117_IADVYY.OPEN_ACCT_RESN AS INTEGER) = 3 THEN 'Transfer'
    WHEN CAST(SRI_101_117_IADVYY.OPEN_ACCT_RESN AS INTEGER) = 4 THEN 'Gaji'
    WHEN CAST(SRI_101_117_IADVYY.OPEN_ACCT_RESN AS INTEGER) = 5 THEN 'Lain-lain' 
 WHEN CAST(SRI_101_117_IADVYY.OPEN_ACCT_RESN AS INTEGER) = 6 THEN 'Simpanan' 
 WHEN CAST(SRI_101_117_IADVYY.OPEN_ACCT_RESN AS INTEGER) = 7 THEN 'Transaksi'
    ELSE NULL END AS OPEN_ACCT_RESN
, CASE WHEN CAST(SRI_101_117_IADVYY.SRC_OF_FUND AS INTEGER) = 1 THEN 'Gaji'
    WHEN CAST(SRI_101_117_IADVYY.SRC_OF_FUND AS INTEGER) = 2 THEN 'Hasil Usaha' 
    WHEN CAST(SRI_101_117_IADVYY.SRC_OF_FUND AS INTEGER) = 3 THEN 'Hasil Investasi' 
    WHEN CAST(SRI_101_117_IADVYY.SRC_OF_FUND AS INTEGER) = 4 THEN 'Hibah/Warisan' 
    WHEN CAST(SRI_101_117_IADVYY.SRC_OF_FUND AS INTEGER) = 5 THEN 'Lain-lain' 
    ELSE NULL END AS SRC_OF_FUND
 
, SRI_101_117_IADVYY.TAPENAS_ACCT 
, CASE WHEN SRI_101_115_DEPP.INSURANCE_FLG = 'I' THEN SRI_101_117_IADVYY.INSU_TERM ELSE 0 END AS TAPENAS_TERM
, ( CONCAT(
 CASE WHEN LENGTH( USER_DEF_CODE_001 ) > 0 THEN COALESCE( USER_DEF_CODE_001  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_002 ) > 0 THEN COALESCE( USER_DEF_CODE_002  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_003 ) > 0 THEN COALESCE( USER_DEF_CODE_003  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_004 ) > 0 THEN COALESCE( USER_DEF_CODE_004  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_005 ) > 0 THEN COALESCE( USER_DEF_CODE_005  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_006 ) > 0 THEN COALESCE( USER_DEF_CODE_006  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_007 ) > 0 THEN COALESCE( USER_DEF_CODE_007  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_008 ) > 0 THEN COALESCE( USER_DEF_CODE_008  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_009 ) > 0 THEN COALESCE( USER_DEF_CODE_009  ,' ')  ELSE '3' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_010 ) > 0 THEN COALESCE( USER_DEF_CODE_010  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_011 ) > 0 THEN COALESCE( USER_DEF_CODE_011  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_012 ) > 0 THEN COALESCE( USER_DEF_CODE_012  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_013 ) > 0 THEN COALESCE( USER_DEF_CODE_013  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_014 ) > 0 THEN COALESCE( USER_DEF_CODE_014  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_015 ) > 0 THEN COALESCE( USER_DEF_CODE_015  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_016 ) > 0 THEN COALESCE( USER_DEF_CODE_016  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_017 ) > 0 THEN COALESCE( USER_DEF_CODE_017  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_018 ) > 0 THEN COALESCE( USER_DEF_CODE_018  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_019 ) > 0 THEN COALESCE( USER_DEF_CODE_019  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_020 ) > 0 THEN COALESCE( USER_DEF_CODE_020  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_021 ) > 0 THEN COALESCE( USER_DEF_CODE_021  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_022 ) > 0 THEN COALESCE( USER_DEF_CODE_022  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_023 ) > 0 THEN COALESCE( USER_DEF_CODE_023  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_024 ) > 0 THEN COALESCE( USER_DEF_CODE_024  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_025 ) > 0 THEN COALESCE( USER_DEF_CODE_025  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_026 ) > 0 THEN COALESCE( USER_DEF_CODE_026  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_027 ) > 0 THEN COALESCE( USER_DEF_CODE_027  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_028 ) > 0 THEN COALESCE( USER_DEF_CODE_028  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_029 ) > 0 THEN COALESCE( USER_DEF_CODE_029  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_030 ) > 0 THEN COALESCE( USER_DEF_CODE_030  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_031 ) > 0 THEN COALESCE( USER_DEF_CODE_031  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_032 ) > 0 THEN COALESCE( USER_DEF_CODE_032  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_033 ) > 0 THEN COALESCE( USER_DEF_CODE_033  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_034 ) > 0 THEN COALESCE( USER_DEF_CODE_034  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_035 ) > 0 THEN COALESCE( USER_DEF_CODE_035  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_036 ) > 0 THEN COALESCE( USER_DEF_CODE_036  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_037 ) > 0 THEN COALESCE( USER_DEF_CODE_037  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_038 ) > 0 THEN COALESCE( USER_DEF_CODE_038  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_039 ) > 0 THEN COALESCE( USER_DEF_CODE_039  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_040 ) > 0 THEN COALESCE( USER_DEF_CODE_040  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_041 ) > 0 THEN COALESCE( USER_DEF_CODE_041  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_042 ) > 0 THEN COALESCE( USER_DEF_CODE_042  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_043 ) > 0 THEN COALESCE( USER_DEF_CODE_043  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_044 ) > 0 THEN COALESCE( USER_DEF_CODE_044  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_045 ) > 0 THEN COALESCE( USER_DEF_CODE_045  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_046 ) > 0 THEN COALESCE( USER_DEF_CODE_046  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_047 ) > 0 THEN COALESCE( USER_DEF_CODE_047  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_048 ) > 0 THEN COALESCE( USER_DEF_CODE_048  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_049 ) > 0 THEN COALESCE( USER_DEF_CODE_049  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_050 ) > 0 THEN COALESCE( USER_DEF_CODE_050  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_051 ) > 0 THEN COALESCE( USER_DEF_CODE_051  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_052 ) > 0 THEN COALESCE( USER_DEF_CODE_052  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_053 ) > 0 THEN COALESCE( USER_DEF_CODE_053  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_054 ) > 0 THEN COALESCE( USER_DEF_CODE_054  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_055 ) > 0 THEN COALESCE( USER_DEF_CODE_055  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_056 ) > 0 THEN COALESCE( USER_DEF_CODE_056  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_057 ) > 0 THEN COALESCE( USER_DEF_CODE_057  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_058 ) > 0 THEN COALESCE( USER_DEF_CODE_058  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_059 ) > 0 THEN COALESCE( USER_DEF_CODE_059  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_060 ) > 0 THEN COALESCE( USER_DEF_CODE_060  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_061 ) > 0 THEN COALESCE( USER_DEF_CODE_061  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_062 ) > 0 THEN COALESCE( USER_DEF_CODE_062  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_063 ) > 0 THEN COALESCE( USER_DEF_CODE_063  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_064 ) > 0 THEN COALESCE( USER_DEF_CODE_064  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_065 ) > 0 THEN COALESCE( USER_DEF_CODE_065  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_066 ) > 0 THEN COALESCE( USER_DEF_CODE_066  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_067 ) > 0 THEN COALESCE( USER_DEF_CODE_067  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_068 ) > 0 THEN COALESCE( USER_DEF_CODE_068  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_069 ) > 0 THEN COALESCE( USER_DEF_CODE_069  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_070 ) > 0 THEN COALESCE( USER_DEF_CODE_070  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_071 ) > 0 THEN COALESCE( USER_DEF_CODE_071  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_072 ) > 0 THEN COALESCE( USER_DEF_CODE_072  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_073 ) > 0 THEN COALESCE( USER_DEF_CODE_073  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_074 ) > 0 THEN COALESCE( USER_DEF_CODE_074  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_075 ) > 0 THEN COALESCE( USER_DEF_CODE_075  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_076 ) > 0 THEN COALESCE( USER_DEF_CODE_076  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_077 ) > 0 THEN COALESCE( USER_DEF_CODE_077  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_078 ) > 0 THEN COALESCE( USER_DEF_CODE_078  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_079 ) > 0 THEN COALESCE( USER_DEF_CODE_079  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_080 ) > 0 THEN COALESCE( USER_DEF_CODE_080  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_081 ) > 0 THEN COALESCE( USER_DEF_CODE_081  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_082 ) > 0 THEN COALESCE( USER_DEF_CODE_082  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_083 ) > 0 THEN COALESCE( USER_DEF_CODE_083  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_084 ) > 0 THEN COALESCE( USER_DEF_CODE_084  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_085 ) > 0 THEN COALESCE( USER_DEF_CODE_085  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_086 ) > 0 THEN COALESCE( USER_DEF_CODE_086  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_087 ) > 0 THEN COALESCE( USER_DEF_CODE_087  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_088 ) > 0 THEN COALESCE( USER_DEF_CODE_088  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_089 ) > 0 THEN COALESCE( USER_DEF_CODE_089  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_090 ) > 0 THEN COALESCE( USER_DEF_CODE_090  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_091 ) > 0 THEN COALESCE( USER_DEF_CODE_091  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_092 ) > 0 THEN COALESCE( USER_DEF_CODE_092  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_093 ) > 0 THEN COALESCE( USER_DEF_CODE_093  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_094 ) > 0 THEN COALESCE( USER_DEF_CODE_094  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_095 ) > 0 THEN COALESCE( USER_DEF_CODE_095  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_096 ) > 0 THEN COALESCE( USER_DEF_CODE_096  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_097 ) > 0 THEN COALESCE( USER_DEF_CODE_097  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_098 ) > 0 THEN COALESCE( USER_DEF_CODE_098  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_099 ) > 0 THEN COALESCE( USER_DEF_CODE_099  ,' ')  ELSE ' ' END ,  
 CASE WHEN LENGTH( USER_DEF_CODE_100 ) > 0 THEN COALESCE( USER_DEF_CODE_100  ,' ')  ELSE ' ' END )
 ) AS USER_DEFINE_CODE
, CASE WHEN SRI_101_115_DEPP.ACCT_DESC = 'T' THEN 'TERM_DEPOSIT' ELSE 'DEPOSIT' END AS DEP_FLAG
, NULL AS AVG_BOOK_BAL 
, NULL AS INT_TAX_AMT 
, NULL AS BLOCK_REASON 
, NULL AS YESTERDAY_END_BAL 
, NULL AS LOWEST_BAL 
, NULL AS HIGHEST_BAL 
, NULL AS ACC_BLOCK_DATE 
, SRI_101_118_INVM.LST_FIN_DT AS LAST_TRX_DATE 
, NULL AS LAST_EOY_BAL 
, NULL AS TAPENAS_ARO_FLAG 
, NULL AS BLOCK_USER_ID 
, NULL AS LAST_MASTER_UPDATE_USER_ID 
, NULL AS INT_RATE_UPDATE_USER_ID 
, NULL AS ROLLOVER_STATUS 
, SRI_101_118_INVM.OWNERSHIP_FLAG AS OWNERSHIP_FLAG
, NULL AS ACC_CLOSE_USER_ID 
, SRI_101_117_IADVYY.AUTO_TRF_CLOSURE
, SRI_101_118_INVM.MIN_BAL_CH_PER
, SRI_101_118_INVM.CHR_EXEM_PROFILE
, SRI_101_118_INVM.DATE_PROCESS AS AS_OF_DATE

FROM PRD_SRI_DATALAKE.SRI_101_118_INVM AS  SRI_101_118_INVM

INNER JOIN PRD_SRI_DATALAKE.SRI_101_115_DEPP AS SRI_101_115_DEPP
ON SRI_101_118_INVM.ACCT_TYPE = SRI_101_115_DEPP.TYPE_1 
AND SRI_101_118_INVM.INT_CAT =  SRI_101_115_DEPP.INT_CAT
AND COALESCE(TRIM(SRI_101_115_DEPP.ISLAMIC_BANK) , 'N') <> 'Y' 
AND SRI_101_115_DEPP.DATE_PROCESS = @tanggal_posisi

LEFT JOIN PRD_SRI_DATALAKE.SRI_101_117_IADVYY AS SRI_101_117_IADVYY
ON SUBSTR(TRIM(SRI_101_118_INVM.KEY_1), 4,16)  = TRIM(SRI_101_117_IADVYY.MEMB_CUST_NO)
AND SRI_101_117_IADVYY.DATE_PROCESS = @tanggal_posisi

LEFT JOIN PRD_SRI_DATALAKE.SRI_101_159_IADVXX AS SRI_101_159_IADVXX
ON SUBSTR(TRIM(SRI_101_118_INVM.KEY_1), 4,16)  = TRIM(SRI_101_159_IADVXX.MEMB_NO)
AND SRI_101_159_IADVXX.DATE_PROCESS = @tanggal_posisi


LEFT JOIN prd_acl_datalake.currency_rate CURRENCY_RATE
ON CURRENCY_RATE.AS_OF_DATE = @tanggal_posisi
AND SRI_101_118_INVM.CURRENCY = CURRENCY_RATE.CURRENCY

WHERE SRI_101_118_INVM.DATE_PROCESS = @tanggal_posisi
AND NOT (CAST(SRI_101_118_INVM.BRANCH_NO AS INTEGER) BETWEEN 800 AND 899);
INSERT INTO prd_acl_datalake.MART_DPK_ICONS
SELECT ID_NUMBER, CIF_KEY, ACCOUNT_TYPE, SUB_CATEGORY, PRODUCT_NAME, CURRENCY, BRANCH_CODE, SUBBRANCH_CODE, ACCT_OPEN_DATE, ACCT_RENEWAL_DT, ACCT_CLOSE_DATE, GL_CLASS_CODE, GL_ACCOUNT_ID, MARKET_SEGMENT_CD, ACCOUNT_STATUS, OLD, OLD, MATURITY_DATE, ORG_TERM, ORG_TERM_MULT, JT, SPECIAL_INT_RATE, JT, RATE, JT, BLOCKED_BALANCE, YTD_INTEREST, INTEREST_ACCRUED, JT, CUR_BOOK_BAL, CUR_BOOK_BAL_IDR, NET_AV_BAL_YTD, NET_AV_NO_YTD, CLR_TRX_TODAY, JT, JT, JT, JT, LAST_PRINT_BAL, LAST_EOM_BAL, DAY FROM #temp_table;
