-- Read from STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM {STAGING_TABLE};

-- Read from TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM {TARGET_TABLE};

-- Update old data
INSERT INTO #TARGET_TABLE
SELECT
cif_key
,cif_open_date
,open_branch_cd
,cust_type
,cust_status
,cust_notice_ind
,salutation_code
,salutation
,title_name
,first_name
,middle_name
,last_name
,company_name
,short_name
,id_type
,id_number
,sex_cd
,birth_date
,birth_place
,citizen_country_cd
,marital_cd
,mother_mdn_name
,cust_user_define_code
,no_of_dependents
,education_cd
,segment_cd
,industry_cd
,bus_sector_code
,religion_cd
,hobby_cd
,country_of_risk_cd
,ivr_flag
,language_flag
,property_ownership_cd
,relation_mgr_cd
,cust_tax_id
,grup_cd
,cust_worst_collectibility
,cust_email
,mail_indicator
,phone_no_res
,phone_no_bus
,fax_no
,hp_no
,home_add_street
,home_add_rtrw
,home_add_kelurahan
,home_add_kecamatan
,home_add_kota_kabupaten
,home_add_provinsi
,home_postcode
,home_city_code
,phone_no_res_ktp
,phone_no_bus_ktp
,fax_no_ktp
,hp_no_ktp
,home_add_street_ktp
,home_add_rtrw_ktp
,home_add_kelurahan_ktp
,home_add_kecamatan_ktp
,home_add_kota_kabupaten_ktp
,home_add_provinsi_ktp
,home_postcode_ktp
,home_city_code_ktp
,res_country_cd
,cust_income
,cust_income_period
,cust_rental_income
,cust_other_income
,cust_ext_deposit_amt
,cust_other_asset_amt
,corp_group_cd
,employer_name
,employed_from
,occupation_cd
,occupation_desc
,office_address1
,office_address2
,office_postcode
,id_expiry_date
,id_issue_date
,id_issue_place
,relation_mgr_name
,tfn_status
,tfn_ind
,domestic_risk
,cross_border_risk
,vip_code
,wtax_exempt
,tax_basis
,bi_owner_cd
,'{TANGGAL_POSISI}' as start_date
,'2999-12-31' as end_date
FROM #STAGING_TABLE
WHERE CIF_KEY IN
(
    SELECT CIF_KEY
    FROM #STAGING_TABLE
    WHERE label = 'UPDATED'
)
AND DATE_ADD('{TANGGAL_POSISI}',-1) BETWEEN START_DATE AND END_DATE;

-- Insert from STAGING_TABLE
INSERT INTO #TARGET_TABLE
SELECT
cif_key
,cif_open_date
,open_branch_cd
,cust_type
,cust_status
,cust_notice_ind
,salutation_code
,salutation
,title_name
,first_name
,middle_name
,last_name
,company_name
,short_name
,id_type
,id_number
,sex_cd
,birth_date
,birth_place
,citizen_country_cd
,marital_cd
,mother_mdn_name
,cust_user_define_code
,no_of_dependents
,education_cd
,segment_cd
,industry_cd
,bus_sector_code
,religion_cd
,hobby_cd
,country_of_risk_cd
,ivr_flag
,language_flag
,property_ownership_cd
,relation_mgr_cd
,cust_tax_id
,grup_cd
,cust_worst_collectibility
,cust_email
,mail_indicator
,phone_no_res
,phone_no_bus
,fax_no
,hp_no
,home_add_street
,home_add_rtrw
,home_add_kelurahan
,home_add_kecamatan
,home_add_kota_kabupaten
,home_add_provinsi
,home_postcode
,home_city_code
,phone_no_res_ktp
,phone_no_bus_ktp
,fax_no_ktp
,hp_no_ktp
,home_add_street_ktp
,home_add_rtrw_ktp
,home_add_kelurahan_ktp
,home_add_kecamatan_ktp
,home_add_kota_kabupaten_ktp
,home_add_provinsi_ktp
,home_postcode_ktp
,home_city_code_ktp
,res_country_cd
,cust_income
,cust_income_period
,cust_rental_income
,cust_other_income
,cust_ext_deposit_amt
,cust_other_asset_amt
,corp_group_cd
,employer_name
,employed_from
,occupation_cd
,occupation_desc
,office_address1
,office_address2
,office_postcode
,id_expiry_date
,id_issue_date
,id_issue_place
,relation_mgr_name
,tfn_status
,tfn_ind
,domestic_risk
,cross_border_risk
,vip_code
,wtax_exempt
,tax_basis
,bi_owner_cd
,'{TANGGAL_POSISI}' as start_date
,'2999-12-31' as end_date
FROM #STAGING_TABLE;

-- Read from #STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from #TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from #STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #TARGET_TABLE;

-- Read from#STAGING_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #STAGING_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#TARGET_TABLE
INSERT INTO #TARGET_TABLE
SELECT * FROM #STAGING_TABLE;

-- Read from#
